###### Examen Demo

In [5]:
# Your imports HERE !!!!
import numpy as np
import pandas as pd

## 01
- Dado un diccionario con una lista de nombres de películas y el año concatenado, crear una función que devuelva un DataFrame con dos columnas:
  - Columna 1, el nombre de la película sin el año
  - Columna 2, el año de la película

In [6]:
movies = {'Name': ["Matrix - 1999", "Cadena Perpetua - 1994", "Parasitos - 2019", "Vengadores, Endgame - 2019", "Interstellar - 2014",
                   "Django Desencadenado - 2012", "El Padrino - 1972", "El Caballero Oscuro - 2008", "Erase Una Vez En America - 1984",
                   "El Senyor de los Anillos, La Comunidad del Anillo - 2001"]}
expected_output = pd.DataFrame({'Name':["Matrix", "Cadena Perpetua", "Parasitos", "Vengadores, Endgame", "Interstellar", "Django Desencadenado",
                                        "El Padrino", "El Caballero Oscuro", "Erase Una Vez En America", "El Senyor de los Anillos, La Comunidad del Anillo"],
                                'Year':["1999", "1994", "2019", "2019", "2014", "2012", "1972", "2008", "1984", "2001"]})
output = extract_year(movies)   # This will call your function extract_year
display(output)
assert(expected_output.equals(output))  # This will fail if the result is not as expected

                                                Name  Year
0                                             Matrix  1999
1                                    Cadena Perpetua  1994
2                                          Parasitos  2019
3                                Vengadores, Endgame  2019
4                                       Interstellar  2014
5                               Django Desencadenado  2012
6                                         El Padrino  1972
7                                El Caballero Oscuro  2008
8                           Erase Una Vez En America  1984
9  El Senyor de los Anillos, La Comunidad del Anillo  2001

In [7]:
# Your solution HERE !!!!
def extract_year(movies):
    def split_year(title):
        index = title.index('-')
        return title[index:].replace('-','').strip()
    
    def remove_year(title):
        index = title.index('-')
        return title[:index-1].strip()

    df_movies = pd.DataFrame(movies)
    df_movies['Year'] = df_movies['Name'].apply(split_year)
    df_movies['Name'] = df_movies['Name'].apply(remove_year)
    
    return df_movies

In [8]:
def extract_year(dicci):
  dicci2={}
  peli=[]
  ano=[]
  for i in dicci['Name']:
    titulo,year=i.split(" - ")
    peli.append(titulo)
    ano.append(int(year))

  dicci2={'Name':peli,'Year':ano}
  frame=pd.DataFrame(dicci2)
  return frame

In [12]:
def extract_year(movies):
  nombres = []
  anios = []
  for titulo in movies['Name']:
    partes = titulo.rsplit(' - ', 1)  
    nombre = partes[0]    
    anio = partes[1]
    nombres.append(nombre)
    anios.append(anio)

  return pd.DataFrame({'Name': nombres, 'Year': anios})

In [11]:
def extract_year(movies):
    df_movies = pd.DataFrame(movies)
    df_movies['Year'] = df_movies['Name'].apply(lambda x : x.split('-')[1].strip())
    df_movies['Name'] = df_movies['Name'].apply(lambda x : x.split('-')[0].strip())
    return df_movies

## 02
- Crear una función que reciba un array de NumPy y devuelva otro en el cual estén marcados como True los elementos duplicados (a partir de la segunda ocurrencia), y como False los no repetidos o las primeras ocurrencias de los duplicados.

In [19]:
# Crea un arreglo de NumPy con los números que se van a analizar
numbers = np.array([4, 4, 4, 3, 8, 1, 9, 6, 1, 5, 9, 4, 0, 2])

# Resultado esperado:
# True  -> el elemento ya había aparecido anteriormente (es un duplicado).
# False -> es la primera vez que aparece ese elemento.
expected_output = np.array([
    False, True, True, False, False, False, False,
    False, True, False, True, True, False, False
])

# Llama a la función find_duplicates para detectar los elementos duplicados
output = find_duplicates(numbers)

# Muestra el resultado obtenido por la función
print(output)

# Comprueba que el resultado obtenido sea exactamente igual al esperado.
# Si no coinciden, se lanzará un AssertionError indicando que la función
# no produjo la salida correcta.
assert(np.array_equal(expected_output, output))

[False  True  True False False False False False  True False  True  True
 False False]

In [16]:
# Your solution HERE !!!!
def find_duplicates(numbers):
    serie = pd.Series(numbers)
    return serie.duplicated()

In [17]:
def find_duplicates(numbers):
    _, idx = np.unique(numbers, return_index = True)
    result = np.zeros_like(numbers, dtype = bool)
    result[idx] = True
    result = np.invert(result)
    return result

In [18]:
def find_duplicates(numbers):
  visto = set()
  output = []
  for value in numbers:
    if value in visto:
      output.append(True)
    else:
      visto.add(value)
      output.append(False)
  return np.array(output)

In [ ]:
def find_duplicates(numeros):
  dicci={}
  resul=np.full(numeros.shape, False, dtype=bool)
  for idx, valor in enumerate(numeros):
    if valor in dicci:
      resul[idx]=True
    else:
      dicci[valor]=True
  return resul

## 03
- Resolución de dos sistemas de ecuaciones
    - $ A : \begin{cases} -9x +  4y = 20 \\ -7y + 16x = 80                         \end{cases}$
    
    - $ B : \begin{cases} x - 2y + 3z = 7 \\ 2x + y + z = 4 \\ -3x + 2y -2z = -10 \end{cases}$
- Verifica por código los resultados

In [4]:
# Importa la biblioteca matemática para usar isclose()
import math

# Importa NumPy con el alias np
import numpy as np

# Importa el módulo de álgebra lineal de NumPy
import numpy.linalg as linalg

# ==========================
# PRIMER SISTEMA DE ECUACIONES
# ==========================

# Matriz de coeficientes
a = np.array([
    [-9, 4],
    [16, -7]
])

# Vector de términos independientes
b = np.array([20, 80])

# Muestra la matriz y el vector
print(a)
print(b)

# Resuelve el sistema Ax = b
x, y = linalg.solve(a, b)

# Imprime la solución
print(f'x = {x}, y = {y}')

# Verifica que la solución satisface las ecuaciones
print(math.isclose(-9*x + 4*y, 20))
print(math.isclose(16*x - 7*y, 80))

# ==========================
# SEGUNDO SISTEMA DE ECUACIONES
# ==========================

# Matriz de coeficientes
A2 = np.array([
    [1, -2, 3],
    [2, 1, 1],
    [-3, 2, -2]
])

# Vector de términos independientes
b2 = np.array([7, 4, -10])

# Resuelve el sistema Ax = b
x, y, z = linalg.solve(A2, b2)

# Imprime la solución
print(f'x = {x}, y = {y}, z = {z}')

# Comprueba que la solución es correcta
print(math.isclose(x - 2*y + 3*z, 7))
print(math.isclose(2*x + y + z, 4))
print(math.isclose(-3*x + 2*y - 2*z, -10))

[[-9  4]
 [16 -7]]
[20 80]
x = 460.0, y = 1040.0
True
True
x = 2.0, y = -1.0, z = 1.0
True
True
True

## 04
- Crear un objeto Series con 10 elementos, que contenga más de un tipo básico, con índices de tipo string
- Demuestra que los datos con índices posicionales son los mismos que los obtenidos con índices semánticos, seleccionando a través de slicing, al menos 4 elementos de la serie anterior

In [24]:
# Importa la biblioteca pandas
import pandas as pd

# Crea una Serie con diferentes tipos de datos y un índice personalizado
serie = pd.Series(
    [1, 2, 3, 4, 5, True, "acelga", 4.5, 9, 10],
    index=list("abcdefghij")
)

# Selecciona los elementos desde el índice 'a' hasta 'd' (incluyéndolo)
# usando etiquetas (loc) y los compara con los primeros cuatro elementos
# seleccionados por posición (iloc).
# El resultado será una Serie de valores booleanos (True si son iguales).
serie.loc[:'d'] == serie.iloc[:4]

a    True
b    True
c    True
d    True
dtype: bool

In [25]:
# Importa la biblioteca pandas
import pandas as pd

# Crea una Serie con valores de tipo texto y un índice personalizado
elementos = pd.Series(
    ['lápiz', '4.13', '33', 'True', 'hola', '123', 'arbol', '5.67', 'mesa', '67'],
    index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
)

# Compara dos formas de seleccionar los mismos elementos:
# - elementos[2:6] selecciona por posición (índices 2, 3, 4 y 5).
# - elementos['c':'f'] selecciona por etiquetas (desde 'c' hasta 'f', inclusive).
# Como ambas selecciones contienen los mismos datos, la comparación devuelve True.
print(elementos[2:6] == elementos['c':'f'])

c    True
d    True
e    True
f    True
dtype: bool

In [26]:
# Importa la biblioteca pandas
import pandas as pd

# Crea una Serie con distintos tipos de datos y un índice personalizado
datos = pd.Series(
    [25, 3.14, "hola", True, 100, "AI", 0.99, False, "Python", 7],
    index=["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"]
)

# Compara dos selecciones equivalentes:
# - iloc[2:6] selecciona por posición (2, 3, 4 y 5).
# - loc["c":"f"] selecciona por etiquetas (desde "c" hasta "f", inclusive).
# Ambas contienen los mismos elementos, por lo que el resultado será True en cada posición.
print(datos.iloc[2:6] == datos.loc["c":"f"])

c    True
d    True
e    True
f    True
dtype: bool

## 05
- Crear un DataFrame de dimensiones 10x10, con números aleatorios en el rango `[0,20]`
- Reemplazar todos aquellos elementos menores de 5 por NaN
- Averiguar cuantos elementos tienen Nan por fila

In [30]:
# Importa las bibliotecas necesarias
import numpy as np
import pandas as pd

# Crea un DataFrame de 10 filas y 10 columnas con números enteros
# aleatorios entre 0 y 20 (21 no se incluye).
df = pd.DataFrame(np.random.randint(21, size=(10, 10)))

# Muestra el DataFrame original
display(df)

# Reemplaza todos los valores menores que 5 por NaN.
# Los valores mayores o iguales a 5 permanecen iguales.
# inplace=True modifica el DataFrame original.
df.where(df >= 5, np.nan, inplace=True)

# Muestra el DataFrame después del reemplazo
display(df)

# Cuenta la cantidad de valores NaN en cada fila.
# axis=1 indica que el conteo se realiza por filas.
print(df.isnull().sum(axis=1))

    0   1   2   3   4   5   6   7   8   9
0  11   4  18  11  20  17  11  13  15   5
1   0  15  20   5  17  14   4  17   8  13
2  17   5   8   3  11  14   9   3   4  18
3   7  15  15   3   3   7  11   7   5  16
4   1   5   9  14  20   6   0   5   0   9
5   5   9   5   0  11  15  18  16   0  18
6  13   4  10   6   5  11   0   4   3  19
7   9  19  19  13  10  14   4  17   8  20
8  20  12   5  15   2  13  11  19  18  11
9  12  13  15  19   2  14   5   3  19  20

      0     1   2     3     4   5     6     7     8   9
0  11.0   NaN  18  11.0  20.0  17  11.0  13.0  15.0   5
1   NaN  15.0  20   5.0  17.0  14   NaN  17.0   8.0  13
2  17.0   5.0   8   NaN  11.0  14   9.0   NaN   NaN  18
3   7.0  15.0  15   NaN   NaN   7  11.0   7.0   5.0  16
4   NaN   5.0   9  14.0  20.0   6   NaN   5.0   NaN   9
5   5.0   9.0   5   NaN  11.0  15  18.0  16.0   NaN  18
6  13.0   NaN  10   6.0   5.0  11   NaN   NaN   NaN  19
7   9.0  19.0  19  13.0  10.0  14   NaN  17.0   8.0  20
8  20.0  12.0   5  15.0   NaN  13  11.0  19.0  18.0  11
9  12.0  13.0  15  19.0   NaN  14   5.0   NaN  19.0  20

0    1
1    2
2    3
3    2
4    3
5    2
6    4
7    1
8    1
9    2
dtype: int64

In [31]:
# Genera una matriz de 10x10 con números enteros aleatorios entre 0 y 20.
matrix = np.random.randint(21, size=(10, 10))

# Convierte la matriz de NumPy en un DataFrame de pandas.
frame = pd.DataFrame(matrix)

# Muestra el DataFrame original.
display(frame)

# Reemplaza todos los valores menores que 5 por NaN.
frame[frame < 5] = np.nan

# Cuenta la cantidad de valores NaN que hay en cada fila.
# axis=1 indica que el conteo se realiza por filas.
nanfila = frame.isna().sum(axis=1)

# Imprime la cantidad de valores NaN de cada fila.
print(nanfila)

    0   1   2   3   4   5   6   7   8   9
0  17   2   2  11  13   0  19   3  15  11
1  16  19  14  10   3   5  11  13   4  16
2  18  12  11   3  16  19  18   4  12  17
3  10   2  14   3  14   0  18  11  17   7
4  17   9  20  18  20   8   8   8  17   2
5   3   1  20  18   4  10  16  14  14   9
6   1   1   2  12  19   7  14  13  10  18
7   2  16  12  18   6  18  13  12   5   8
8   5  13   1   7   0  10  19  19  11  19
9  19  12  11   7   7  12   2   6   9  13

0    4
1    2
2    2
3    3
4    1
5    3
6    3
7    1
8    2
9    1
dtype: int64

In [32]:
# Importa las bibliotecas necesarias
import numpy as np
import pandas as pd

# Crea un DataFrame de 10 filas y 10 columnas con números enteros
# aleatorios entre 0 y 19 (20 no se incluye).
df = pd.DataFrame(np.random.randint(0, 20, size=(10, 10)))

# Muestra el DataFrame original.
print("DataFrame original:\n", df)

# Reemplaza todos los valores menores que 5 por NaN.
# Los valores mayores o iguales a 5 permanecen sin cambios.
df[df < 5] = np.nan

# Muestra el DataFrame después de reemplazar los valores.
print("\nDataFrame con NaNs:\n", df)

# Cuenta cuántos valores NaN hay en cada fila.
# axis=1 indica que el conteo se realiza horizontalmente (por filas).
nans_por_fila = df.isna().sum(axis=1)

# Imprime la cantidad de valores NaN de cada fila.
print("\nCantidad de NaNs por fila:\n", nans_por_fila)

DataFrame original:
     0   1   2   3   4   5   6   7   8   9
0   2   6  19  14  19  14  19   1   0  18
1  13  13   0  19   8  10   3  15  10   6
2   4   8  18  16   0   3   2   4   3   5
3  16   8  11  18   7  13  15   4  16   7
4  12  13   7   5   5  16   7  10   0   5
5   9   9  12  10   8   8   2  16  14   7
6   8   3   1   4  17   5  14  16   4   3
7   6  14  15  12  11   0  16   0   3  16
8  16   9   9   3   5  19  10   4   9   9
9  14  16  13   5   5  13  18   1   3  10

DataFrame con NaNs:
       0     1     2     3     4     5     6     7     8     9
0   NaN   6.0  19.0  14.0  19.0  14.0  19.0   NaN   NaN  18.0
1  13.0  13.0   NaN  19.0   8.0  10.0   NaN  15.0  10.0   6.0
2   NaN   8.0  18.0  16.0   NaN   NaN   NaN   NaN   NaN   5.0
3  16.0   8.0  11.0  18.0   7.0  13.0  15.0   NaN  16.0   7.0
4  12.0  13.0   7.0   5.0   5.0  16.0   7.0  10.0   NaN   5.0
5   9.0   9.0  12.0  10.0   8.0   8.0   NaN  16.0  14.0   7.0
6   8.0   NaN   NaN   NaN  17.0   5.0  14.0  16.0   NaN   NaN
7   6.0  14.0  15.0  12.0  11.0   NaN  16.0   NaN   NaN  16.0
8  16.0   9.0   9.0   NaN   5.0  19.0  10.0   NaN   9.0   9.0
9  14.0  16.0  13.0   5.0   5.0  13.0  18.0   NaN   NaN  10.0

Cantidad de NaNs por fila:
 0    3
1    2
2    6
3    1
4    1
5    1
6    5
7    3
8    2
9    2
dtype: int64

## 06
- Dada una lista de elementos, crea una función que devuelva un dataframe sin los elementos duplicados

In [37]:
# Crea una lista con algunos elementos repetidos.
serie = ['a', 'b', 'c', 'a', 'c', 'a', 'g']

# Crea un DataFrame con el resultado esperado,
# donde solo aparecen los valores únicos,
# conservando el orden de su primera aparición.
expected_output = pd.DataFrame(['a', 'b', 'c', 'g'])

# Llama a la función remove_duplicates(), que debe eliminar
# los elementos duplicados de la lista y devolver un DataFrame.
output = remove_duplicates(serie)

# Muestra el resultado obtenido por la función.
display(output)

# Muestra el resultado esperado para compararlo visualmente.
display(expected_output)

# Verifica que el DataFrame obtenido sea exactamente igual
# al DataFrame esperado.
# Si no son iguales, se producirá un AssertionError.
assert(expected_output.equals(output))

   0
0  a
1  b
2  c
3  g

   0
0  a
1  b
2  c
3  g

In [34]:
# Función que elimina elementos duplicados de una lista
# manteniendo el orden en el que aparecen.
def remove_duplicates(lista):
    
    # Crea una lista vacía para guardar los elementos únicos.
    unicos = []
    
    # Recorre cada elemento de la lista original.
    for elemento in lista:
        
        # Si el elemento todavía no está en la lista de únicos,
        # lo añade.
        if elemento not in unicos:
            unicos.append(elemento)
    
    # Convierte la lista de elementos únicos en un DataFrame
    # y lo devuelve.
    return pd.DataFrame(unicos)

In [35]:
# Función que elimina elementos repetidos de una lista
def remove_duplicates(lista):
    
    # Convierte la lista en un conjunto (set).
    # Un set elimina automáticamente los valores duplicados.
    # IMPORTANTE: no garantiza mantener el orden original.
    noduplis = list(set(lista))
    
    # Convierte la lista sin duplicados en un DataFrame.
    # La columna se llama "elementos".
    df = pd.DataFrame(noduplis, columns=['elementos'])
    
    # Devuelve el DataFrame creado.
    return df

In [36]:
# Función que elimina elementos duplicados de una lista
def remove_duplicates(lista):
    
    # Crea un diccionario usando los elementos de la lista como claves.
    # Los diccionarios no permiten claves repetidas, por lo que elimina duplicados.
    # Además, conserva el orden de la primera aparición de cada elemento.
    unicos = list(dict.fromkeys(lista))
    
    # Convierte la lista de elementos únicos en un DataFrame de pandas
    # y lo devuelve.
    return pd.DataFrame(unicos)

## 07 - 1pt
- Escribir un generador `frange` que simule el comportamiento de la función `arange` de NumPy
- Esta función cada vez que se invoque debe devolver valores espaciados uniformemente a partir de un valor inicial. Se debe proveer a dicha función un valor inicial para la secuencia de números y un valor para el step
- Debe soportar valores númericos en coma flotante
- La función potencialmente se puede llamar un número infinito de veces
- Usando plain Python, sin ninguna librería

In [40]:
# Importa la librería matemática para usar math.isclose()
import math

# Valor inicial de la secuencia
init = 10.6

# Incremento que tendrá cada número
step = 0.8

# Crea el generador llamando a la función frange()
g = frange(init, step)

# Cantidad de valores que se quieren obtener
iters = 10

# Obtiene los primeros 10 valores del generador
numbers = [next(g) for n in range(iters)]

# Comprueba que cada valor generado sea igual a:
# inicio + (incremento * posición)
for i, n in enumerate(numbers):
    assert(math.isclose(n, init + (step * i)))

# Muestra la lista de números generados
print(numbers)

[10.6, 11.4, 12.200000000000001, 13.000000000000002, 13.800000000000002, 14.600000000000003, 15.400000000000004, 16.200000000000003, 17.000000000000004, 17.800000000000004]

In [39]:
def frange(init, step):
    # Guarda el valor actual de la secuencia
    actual = init
    
    # Genera valores infinitamente
    while True:
        yield actual
        
        # Incrementa el valor para la siguiente iteración
        actual += step

## 08
- Crear una función que reciba una Serie de Pandas y devuelva esa misma serie, reemplazando los espacios en blanco por el carácter menos frecuente en dicha serie.

In [53]:
# Crea una Serie de pandas a partir de una lista de caracteres.
# La cadena contiene espacios en blanco que deben ser limpiados.
serie = pd.Series(list('bba cabc faabba aacbbfe'))

# Define el resultado esperado después de limpiar los espacios.
# Los espacios deben eliminarse, dejando solamente los caracteres.
expected_output = pd.Series(list('bbaecabcefaabbaeaacbbfe'))

# Llama a la función clean_whitespace_replace().
# Esta función debe eliminar o reemplazar los espacios en blanco de la Serie.
output = clean_whitespace_replace(serie)

# Comprueba que el resultado obtenido sea exactamente igual al esperado.
# Si no coincide, se genera un AssertionError.
assert(expected_output.equals(output))

In [51]:
def clean_whitespace_replace(serie):
    # Une todos los elementos de la Serie en un solo texto,
    # elimina los espacios y vuelve a crear una Serie de caracteres.
    texto = ''.join(serie).replace(' ', '')
    
    return pd.Series(list(texto))

In [52]:
from collections import Counter

# Función para limpiar/reemplazar espacios en una Serie
def clean_whitespace_replace(seri):
    
    # Une todos los elementos de la Serie en un solo texto.
    # dropna() elimina valores vacíos (NaN).
    # astype(str) convierte todos los elementos a texto.
    texto = ''.join(seri.dropna().astype(str))
    
    # Cuenta la frecuencia de cada carácter del texto.
    # Ignora los caracteres vacíos.
    frecu = Counter(i for i in texto if i != '')
    
    # Busca el carácter que aparece menos veces.
    mefrecu = min(frecu, key=frecu.get)
    
    # Reemplaza cada espacio ' ' por el carácter menos frecuente.
    seridif = seri.astype(str).apply(lambda s: s.replace(' ', mefrecu))
    
    # Devuelve la Serie modificada.
    return seridif