![logo](img/logoitqv1.jpg)
<br>
# 0.1 PAO26-26 - Python 101, Pandas 2
<br>

![python](img/python_logo.png)

<br>

*Kenin Cusme*

<br>

[link de Git Hub](https://github.com/kenin395/Machine-Learning.git)

In [1]:
# Instalar pandas en el Python que usa este notebook
import sys
import subprocess

subprocess.run(
    [sys.executable, "-m", "pip", "install", "pandas", "numpy", "matplotlib", "-q"],
    check=False,
)

print("Python:", sys.executable)

Python: C:\Users\Jesus\anaconda3\python.exe

In [2]:
import pandas as pd
import numpy as np
from IPython.display import display

In [3]:
pd.__version__

'3.0.3'

# 1 Operaciones en pandas

## Búsqueda

In [4]:
rand_matrix = np.random.randint(6, size=(2, 3))
frame = pd.DataFrame(rand_matrix, columns=list("ABC"))
display(frame)

   A  B  C
0  1  1  3
1  3  2  4

In [5]:
# buscando columnas (DataFrame como dic, busca en claves)
'A' in frame

True

In [6]:
# buscando valores
display(frame.isin([3, 2]))  # --> mask de respuesta (valores que son 3 o 2)

       A      B      C
0  False  False   True
1   True   True  False

In [7]:
# Contar el número de ocurrencias
print(frame.isin([4]).values.sum())
display(frame.isin([4]))  # devuelve una mask con valores true si el elemento es 4
print(frame.isin([4]).values)

1

       A      B      C
0  False  False  False
1  False  False   True

[[False False False]
 [False False  True]]

In [8]:
type(frame.isin([4]).values)  # pandas es una capa alrededor de numpy

numpy.ndarray

In [9]:
# Cuántos valores son >= 2
mask = frame >= 2
print(mask.values.sum())
display(mask)

4

       A      B     C
0  False  False  True
1   True   True  True

## Ordenación

In [10]:
from random import shuffle

rand_matrix = np.random.randint(20, size=(5, 4))
indices = list(range(5))
shuffle(indices)  # mezcla indices
frame = pd.DataFrame(rand_matrix, columns=list("DACB"), index=indices)
display(frame)

    D   A   C   B
4  11   4   9   4
0   1   0   3   4
3  13  16  17   2
2  19   2  13  12
1   7   4  12   7

In [11]:
# ordenar por índice
display(frame.sort_index(ascending=False))
display(frame)

    D   A   C   B
4  11   4   9   4
3  13  16  17   2
2  19   2  13  12
1   7   4  12   7
0   1   0   3   4

    D   A   C   B
4  11   4   9   4
0   1   0   3   4
3  13  16  17   2
2  19   2  13  12
1   7   4  12   7

In [12]:
# ordenar por columna
display(frame.sort_index(axis=1, ascending=False))

    D   C   B   A
4  11   9   4   4
0   1   3   4   0
3  13  17   2  16
2  19  13  12   2
1   7  12   7   4

In [13]:
# ordenar filas por valor en columna
display(frame.sort_values(by='A', ascending=True))

    D   A   C   B
0   1   0   3   4
2  19   2  13  12
4  11   4   9   4
1   7   4  12   7
3  13  16  17   2

In [14]:
# ordenar columnas por valor en fila
display(frame.sort_values(by=1, axis=1, ascending=True))

    A   D   B   C
4   4  11   4   9
0   0   1   4   3
3  16  13   2  17
2   2  19  12  13
1   4   7   7  12

In [15]:
# ordenar por valor en columna y guardar cambios
frame.sort_values(by='A', ascending=False, inplace=True)
display(frame)

    D   A   C   B
3  13  16  17   2
4  11   4   9   4
1   7   4  12   7
2  19   2  13  12
0   1   0   3   4

## Ranking

• Construir un ranking de valores

In [16]:
display(frame)

    D   A   C   B
3  13  16  17   2
4  11   4   9   4
1   7   4  12   7
2  19   2  13  12
0   1   0   3   4

In [17]:
display(frame.rank(method='max', axis=1))

     D    A    C    B
3  2.0  3.0  4.0  1.0
4  4.0  2.0  3.0  2.0
1  3.0  1.0  4.0  3.0
2  4.0  1.0  3.0  2.0
0  2.0  1.0  3.0  4.0

In [18]:
# Imprimir, uno a uno, los valores de la columna 'C' de mayor a menor
for x in frame.sort_values(by='C', ascending=False)['C'].values:
    print(x)

17
13
12
9
3

# 2 Operaciones

## Operaciones matemáticas entre objetos

In [19]:
matrixA = np.random.randint(100, size=(4, 4))
matrixB = np.random.randint(100, size=(4, 4))
frameA = pd.DataFrame(matrixA)
frameB = pd.DataFrame(matrixB)
display(frameA)
display(frameB)

    0   1   2   3
0  14  34  62  91
1  48  58  20  33
2  57  37  48  38
3  53  85  16  98

    0   1   2   3
0  15  24   8  18
1  37   1  74  97
2   3  53  28  60
3  83  59  90  54

In [20]:
# a través de métodos u operadores
display(frameA + frameB == frameA.add(frameB))
display(frameA + frameB)

      0     1     2     3
0  True  True  True  True
1  True  True  True  True
2  True  True  True  True
3  True  True  True  True

     0    1    2    3
0   29   58   70  109
1   85   59   94  130
2   60   90   76   98
3  136  144  106  152

In [21]:
display(frameB - frameA == frameB.sub(frameA))
display(frameB - frameA)

      0     1     2     3
0  True  True  True  True
1  True  True  True  True
2  True  True  True  True
3  True  True  True  True

    0   1   2   3
0   1 -10 -54 -73
1 -11 -57  54  64
2 -54  16 -20  22
3  30 -26  74 -44

In [22]:
# si los frames no son iguales, valor por defecto NaN
frameC = pd.DataFrame(np.random.randint(100, size=(3, 3)))
display(frameA)
display(frameC)
display(frameC + frameA)

    0   1   2   3
0  14  34  62  91
1  48  58  20  33
2  57  37  48  38
3  53  85  16  98

    0   1   2
0  12  57  68
1  64  73  92
2   2  90  77

       0      1      2   3
0   26.0   91.0  130.0 NaN
1  112.0  131.0  112.0 NaN
2   59.0  127.0  125.0 NaN
3    NaN    NaN    NaN NaN

In [23]:
# se puede especificar el valor por defecto con el argumento fill_value
display(frameA.add(frameC, fill_value=0))

       0      1      2     3
0   26.0   91.0  130.0  91.0
1  112.0  131.0  112.0  33.0
2   59.0  127.0  125.0  38.0
3   53.0   85.0   16.0  98.0

## Operadores aritméticos solo válidos en elementos aceptables

In [24]:
frameD = pd.DataFrame({0: ['a', 'b'], 1: ['d', 'f']})
display(frameD)
try:
    frameA - frameD
except TypeError as e:
    print(type(e).__name__ + ":", e)

   0  1
0  a  d
1  b  f

TypeError: operation 'rsub' not supported for dtype 'str' with dtype 'int32'

## Operaciones entre Series y DataFrames

In [25]:
rand_matrix = np.random.randint(10, size=(3, 4))
df = pd.DataFrame(rand_matrix, columns=list("ABCD"))
display(df)
display(df.iloc[0])
display(type(df.iloc[0]))
# uso común, averiguar la diferencia entre una fila y el resto
display(df - df.iloc[0])
display(df.sub(df.iloc[0], axis=1))
# Por columnas cómo se restaría
display(df.sub(df['A'], axis=0))

   A  B  C  D
0  3  3  3  3
1  9  5  5  2
2  3  1  7  2

A    3
B    3
C    3
D    3
Name: 0, dtype: int32

pandas.Series

   A  B  C  D
0  0  0  0  0
1  6  2  2 -1
2  0 -2  4 -1

   A  B  C  D
0  0  0  0  0
1  6  2  2 -1
2  0 -2  4 -1

   A  B  C  D
0  0  0  0  0
1  0 -4 -4 -7
2  0 -2  4 -1

pandas se basa en NumPy, np operadores binarios y unarios son aceptables

| Tipo | Operación | Descripción |
|------|-----------|-------------|
| Unario | abs | Valor absoluto de cada elemento |
| Unario | sqrt | Raíz cuadrada de cada elemento |
| Unario | exp | e^x, siendo x cada elemento |
| Unario | log, log10, log2 | Logaritmos en distintas bases de cada elemento |
| Unario | sign | Retorna el signo de cada elemento (-1 para negativo, 0 o 1 para positivo) |
| Unario | ceil | Redondea cada elemento por arriba |
| Unario | floor | Redondea cada elemento por abajo |
| Unario | isnan | Retorna si cada elemento es NaN |
| Unario | cos, sin, tan | Operaciones trigonométricas en cada elemento |
| Unario | arccos, arcsin, arctan | Inversas de operaciones trigonométricas en cada elemento |
| Binario | add | Suma de dos arrays |
| Binario | substract | Resta de dos arrays |
| Binario | multiply | Multiplicación de dos arrays |
| Binario | divide | División de dos arrays |
| Binario | maximum, minimum | Retorna el valor máximo/mínimo de cada pareja de elementos |
| Binario | equal, not_equal | Retorna la comparación (igual o no igual) de cada pareja de elementos |
| Binario | greater, greater_equal, less, less_equal | Retorna la comparación (>, >=, <, <=) de cada pareja de elementos |

## Aplicación de funciones a medida con lambda

In [26]:
rand_matrix = np.random.randint(10, size=(3, 4))
frame = pd.DataFrame(rand_matrix, columns=list("ABCD"))
display(frame)
print(frame.apply(lambda x: x.max() - x.min(), axis=1))  # diferencia por columna

   A  B  C  D
0  7  8  3  3
1  6  3  3  4
2  9  0  6  5

0    5
1    3
2    9
dtype: int64

In [27]:
def max_min(x):
    return x.max() - x.min()

print(frame.apply(max_min, axis=0))  # diferencia por columna

A    3
B    8
C    3
D    2
dtype: int64

In [28]:
# diferencia entre min y max por fila (no columna)
rand_matrix = np.random.randint(10, size=(3, 4))
frame = pd.DataFrame(rand_matrix, columns=list("ABCD"))
display(frame)
print(frame.apply(lambda x: x.max() - x.min(), axis=1))  # diferencia por fila

   A  B  C  D
0  3  5  3  5
1  3  9  4  4
2  6  6  0  6

0    2
1    6
2    6
dtype: int64

# 3 Estadística descriptiva

• Análisis preliminar de los datos
• Para Series y DataFrame

| Operación | Descripción |
|-----------|-------------|
| count | Número de valores no NaN |
| describe | Conjunto de estadísticas sumarias |
| min, max | Valores mínimo y máximo |
| argmin, argmax | Índices posicionales del valor mínimo y máximo |
| idxmin, idxmax | Índices semánticos del valor mínimo y máximo |
| sum | Suma de los elementos |
| mean | Media de los elementos |
| median | Mediana de los elementos |
| mad | Desviación absoluta media del valor medio |
| var | Varianza de los elementos |
| std | Desviación estándar de los elementos |
| cumsum | Suma acumulada de los elementos |
| diff | Diferencia aritmética de los elementos |

In [29]:
diccionario = {
    "nombre": ["Marisa", "Laura", "Manuel", "Carlos"],
    "edad": [34, 34, 11, 30],
    "puntos": [98, 12, 98, np.nan],
    "genero": ["F", "F", "M", "M"],
}
frame = pd.DataFrame(diccionario)
display(frame)
display(frame.describe())  # datos generales de elementos

   nombre  edad  puntos genero
0  Marisa    34    98.0      F
1   Laura    34    12.0      F
2  Manuel    11    98.0      M
3  Carlos    30     NaN      M

            edad     puntos
count   4.000000   3.000000
mean   27.250000  69.333333
std    10.996211  49.652123
min    11.000000  12.000000
25%    25.250000  55.000000
50%    32.000000  98.000000
75%    34.000000  98.000000
max    34.000000  98.000000

In [30]:
# operadores básicos
print(frame.sum())
display(frame)
print(frame.sum(axis=1, numeric_only=True))

nombre    MarisaLauraManuelCarlos
edad                          109
puntos                      208.0
genero                       FFMM
dtype: object

   nombre  edad  puntos genero
0  Marisa    34    98.0      F
1   Laura    34    12.0      F
2  Manuel    11    98.0      M
3  Carlos    30     NaN      M

0    132.0
1     46.0
2    109.0
3     30.0
dtype: float64

In [31]:
frame.mean(numeric_only=True)

edad      27.250000
puntos    69.333333
dtype: float64

In [32]:
frame.cumsum()

                    nombre  edad  puntos genero
0                   Marisa    34    98.0      F
1              MarisaLaura    68   110.0     FF
2        MarisaLauraManuel    79   208.0    FFM
3  MarisaLauraManuelCarlos   109     NaN   FFMM

In [33]:
frame.count(axis=1)

0    4
1    4
2    4
3    3
dtype: int64

In [34]:
print(frame['edad'].std())

10.996211468804457

In [35]:
frame['edad'].idxmax()

0

In [36]:
frame['puntos'].idxmin()

1

In [37]:
# frame con las filas con los valores maximos de una columna
print(frame['puntos'].max())
display(frame[frame['puntos'] == frame['puntos'].max()])

98.0

   nombre  edad  puntos genero
0  Marisa    34    98.0      F
2  Manuel    11    98.0      M

In [38]:
frame["ranking"] = frame["puntos"].rank(method="max")

In [39]:
display(frame)

   nombre  edad  puntos genero  ranking
0  Marisa    34    98.0      F      3.0
1   Laura    34    12.0      F      1.0
2  Manuel    11    98.0      M      3.0
3  Carlos    30     NaN      M      NaN

## 3.1 Agregaciones

In [40]:
display(frame)
df = frame.groupby('genero').count()
display(df)

   nombre  edad  puntos genero  ranking
0  Marisa    34    98.0      F      3.0
1   Laura    34    12.0      F      1.0
2  Manuel    11    98.0      M      3.0
3  Carlos    30     NaN      M      NaN

        nombre  edad  puntos  ranking
genero
F            2     2       2        2
M            2     2       1        1

In [41]:
# si es Nan descarta la fila
df = frame.groupby('puntos').count()
display(df)

        nombre  edad  genero  ranking
puntos
12.0         1     1       1        1
98.0         2     2       2        2

In [42]:
display(frame.groupby('genero').mean(numeric_only=True))

        edad  puntos  ranking
genero
F       34.0    55.0      2.0
M       20.5    98.0      3.0

In [43]:
display(frame.groupby('genero').max())

        nombre  edad  puntos  ranking
genero
F       Marisa    34    98.0      3.0
M       Manuel    30    98.0      3.0

In [44]:
# funciones de agregación de varias columnas para obtener distintos estadísticos
display(frame.groupby('genero')[['edad', 'puntos']].aggregate(['min', 'mean', 'max']))

       edad           puntos
        min  mean max    min  mean   max
genero
F        34  34.0  34   12.0  55.0  98.0
M        11  20.5  30   98.0  98.0  98.0

In [45]:
# Filtrado de los datos en el que el conjunto no supera una media determinada
def media(x):
    return x["edad"].mean() > 30

display(frame)
frame.groupby('genero').filter(media)

   nombre  edad  puntos genero  ranking
0  Marisa    34    98.0      F      3.0
1   Laura    34    12.0      F      1.0
2  Manuel    11    98.0      M      3.0
3  Carlos    30     NaN      M      NaN

   nombre  edad  puntos genero  ranking
0  Marisa    34    98.0      F      3.0
1   Laura    34    12.0      F      1.0

## 3.2 Correlaciones

pandas incluye métodos para analizar correlaciones - Relación matemática entre dos variables
(-1 negativamente relacionadas, 1 positivamente relacionadas, 0 sin relación)
- obj.corr(obj2) -> medida de correlación entre los datos de ambos objetos
- https://blogs.oracle.com/ai-and-datascience/post/introduction-to-correlation

### 3.2.1 Ejemplo Fuel efficiency

• https://archive.ics.uci.edu/ml/datasets/Auto+MPG

In [46]:
path = 'http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data'
mpg_data = pd.read_csv(
    path,
    sep=r'\s+',
    header=None,
    names=['mpg', 'cilindros', 'desplazamiento', 'potencia',
           'peso', 'aceleracion', 'año', 'origen', 'nombre'],
    na_values='?',
    engine='c',
)

In [47]:
display(mpg_data.sample(5))

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion,año,origen,nombre
143,26.0,4,97.0,78.0,2300.0,14.5,74,2,opel manta
390,32.0,4,144.0,96.0,2665.0,13.9,82,3,toyota celica gt
218,36.0,4,79.0,58.0,1825.0,18.6,77,2,renault 5 gtl
195,29.0,4,85.0,52.0,2035.0,22.2,76,1,chevrolet chevette
47,19.0,6,250.0,100.0,3282.0,15.0,71,1,pontiac firebird

In [48]:
display(mpg_data.describe(include='all'))

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion,año,origen,nombre
count,398.000000,398.000000,398.000000,392.000000,398.000000,398.000000,398.000000,398.000000,398
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,305
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ford pinto
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
mean,23.514573,5.454774,193.425879,104.469388,2970.424623,15.568090,76.010050,1.572864,NaN
std,7.815984,1.701004,104.269838,38.491160,846.841774,2.757689,3.697627,0.802055,NaN
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000,1.000000,NaN
25%,17.500000,4.000000,104.250000,75.000000,2223.750000,13.825000,73.000000,1.000000,NaN
50%,23.000000,4.000000,148.500000,93.500000,2803.500000,15.500000,76.000000,1.000000,NaN
75%,29.000000,8.000000,262.000000,126.000000,3608.000000,17.175000,79.000000,2.000000,NaN
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000,3.000000,NaN

In [49]:
mpg_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   mpg             398 non-null    float64
 1   cilindros       398 non-null    int64
 2   desplazamiento  398 non-null    float64
 3   potencia        392 non-null    float64
 4   peso            398 non-null    float64
 5   aceleracion     398 non-null    float64
 6   año             398 non-null    int64
 7   origen          398 non-null    int64
 8   nombre          398 non-null    str
dtypes: float64(5), int64(3), str(1)
memory usage: 34.4 KB

### 3.2.2 Correlaciones entre valores

In [50]:
mpg_data['mpg'].corr(mpg_data['peso'])  # + mpg = - peso

np.float64(-0.8317409332443354)

In [51]:
mpg_data['peso'].corr(mpg_data['aceleracion'])  # + peso = - aceleracion

np.float64(-0.41745731994039337)

### 3.2.3 Correlaciones entre todos los valores

In [52]:
mpg_data.corr(numeric_only=True)

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion,año,origen
mpg,1.000000,-0.775396,-0.804203,-0.778427,-0.831741,0.420289,0.579267,0.563450
cilindros,-0.775396,1.000000,0.950721,0.842983,0.896017,-0.505419,-0.348746,-0.562543
desplazamiento,-0.804203,0.950721,1.000000,0.897257,0.932824,-0.543684,-0.370164,-0.609409
potencia,-0.778427,0.842983,0.897257,1.000000,0.864538,-0.689196,-0.416361,-0.455171
peso,-0.831741,0.896017,0.932824,0.864538,1.000000,-0.417457,-0.306564,-0.581024
aceleracion,0.420289,-0.505419,-0.543684,-0.689196,-0.417457,1.000000,0.288137,0.205873
año,0.579267,-0.348746,-0.370164,-0.416361,-0.306564,0.288137,1.000000,0.180662
origen,0.563450,-0.562543,-0.609409,-0.455171,-0.581024,0.205873,0.180662,1.000000

In [53]:
# año y origen no parecen correlacionables
# eliminar columnas de la correlacion
corr_data = mpg_data.drop(['año', 'origen'], axis=1).corr(numeric_only=True)
display(corr_data)

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion
mpg,1.000000,-0.775396,-0.804203,-0.778427,-0.831741,0.420289
cilindros,-0.775396,1.000000,0.950721,0.842983,0.896017,-0.505419
desplazamiento,-0.804203,0.950721,1.000000,0.897257,0.932824,-0.543684
potencia,-0.778427,0.842983,0.897257,1.000000,0.864538,-0.689196
peso,-0.831741,0.896017,0.932824,0.864538,1.000000,-0.417457
aceleracion,0.420289,-0.505419,-0.543684,-0.689196,-0.417457,1.000000

In [54]:
# representación gráfica matplotlib
import matplotlib.pyplot as plt

In [55]:
# representación gráfica
corr_data.style.background_gradient(cmap=plt.get_cmap('RdYlGn'), axis=1)

In [56]:
# correlación más negativa
mpg_data.drop(['año', 'origen'], axis=1).corr(numeric_only=True).idxmin()

mpg                   peso
cilindros              mpg
desplazamiento         mpg
potencia               mpg
peso                   mpg
aceleracion       potencia
dtype: str

In [57]:
# correlación más positiva
mpg_data.drop(['año', 'origen'], axis=1).corr(numeric_only=True).idxmax()  # consigo misma....

mpg                          mpg
cilindros              cilindros
desplazamiento    desplazamiento
potencia                potencia
peso                        peso
aceleracion          aceleracion
dtype: str

In [58]:
# tabla similar con las correlaciones más positivas (evitar parejas del mismo valor)
positive_corr = mpg_data.drop(['año', 'origen'], axis=1).corr(numeric_only=True).copy()
for col in positive_corr.index:
    positive_corr.at[col, col] = 0
display(positive_corr)
positive_corr.idxmax()

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion
mpg,0.000000,-0.775396,-0.804203,-0.778427,-0.831741,0.420289
cilindros,-0.775396,0.000000,0.950721,0.842983,0.896017,-0.505419
desplazamiento,-0.804203,0.950721,0.000000,0.897257,0.932824,-0.543684
potencia,-0.778427,0.842983,0.897257,0.000000,0.864538,-0.689196
peso,-0.831741,0.896017,0.932824,0.864538,0.000000,-0.417457
aceleracion,0.420289,-0.505419,-0.543684,-0.689196,-0.417457,0.000000

mpg                  aceleracion
cilindros         desplazamiento
desplazamiento         cilindros
potencia          desplazamiento
peso              desplazamiento
aceleracion                  mpg
dtype: str

In [59]:
positive_corr.style.background_gradient(cmap=plt.get_cmap('RdYlGn'), axis=1, vmin=-1.0, vmax=1.0)

## 3.3 Ejercicios

• Ejercicios para practicar Pandas: https://github.com/ajcr/100-pandas-puzzles/blob/master/100-pandas-puzzles.ipynb